import { describe, it, expect, beforeEach, afterEach } from 'vitest';
import * as fs from 'fs';
import * as os from 'os';
import * as path from 'path';
import {
  detectPackageManager,
  getPackageManagerInfo,
  getInstallCommand,
  getUninstallCommand,
  getAuditCommand,
  getAuditCommandForProject,
  isYarnBerry,
  parseAuditOutput,
} from '../packageManagerService';
import type { PackageManager } from '../../../types';

describe('detectPackageManager', () => {
  let projectPath: string;

  beforeEach(() => {
    projectPath = fs.mkdtempSync(path.join(os.tmpdir(), 'nvm-detect-'));
  });

  afterEach(() => {
    fs.rmSync(projectPath, { recursive: true, force: true });
  });

  const writeLockFile = (name: string): void => {
    fs.writeFileSync(path.join(projectPath, name), '');
  };

  it('defaults to npm when no lock file is present', async () => {
    await expect(detectPackageManager(projectPath)).resolves.toBe('npm');
  });

  it.each([
    ['package-lock.json', 'npm'],
    ['yarn.lock', 'yarn'],
    ['pnpm-lock.yaml', 'pnpm'],
  ] as Array<[string, PackageManager]>)('detects %s as %s', async (lockFile, expected) => {
    writeLockFile(lockFile);
    await expect(detectPackageManager(projectPath)).resolves.toBe(expected);
  });

  // Bun 1.2 switched from the binary bun.lockb to the text bun.lock. Only
  // bun.lockb used to be recognised, so every modern bun project silently fell
  // through to the npm default and got npm commands run against it.
  it('detects bun from the current text lock file (bun.lock)', async () => {
    writeLockFile('bun.lock');
    await expect(detectPackageManager(projectPath)).resolves.toBe('bun');
  });

  it('still detects bun from the legacy binary lock file (bun.lockb)', async () => {
    writeLockFile('bun.lockb');
    await expect(detectPackageManager(projectPath)).resolves.toBe('bun');
  });

  it('detects bun when both lock file formats are present', async () => {
    writeLockFile('bun.lock');
    writeLockFile('bun.lockb');
    await expect(detectPackageManager(projectPath)).resolves.toBe('bun');
  });

  it('ignores a directory named like a lock file', async () => {
    fs.mkdirSync(path.join(projectPath, 'pnpm-lock.yaml'));
    // fs.access only proves the path exists, so this documents current
    // behaviour rather than asserting it is ideal.
    await expect(detectPackageManager(projectPath)).resolves.toBe('pnpm');
  });
});

describe('lock file declarations', () => {
  it('lists every known bun lock file, most current format first', () => {
    expect(getPackageManagerInfo('bun').lockFiles).toEqual(['bun.lock', 'bun.lockb']);
  });

  it.each(['npm', 'yarn', 'pnpm', 'bun'] as PackageManager[])('declares at least one lock file for %s', manager => {
    expect(getPackageManagerInfo(manager).lockFiles.length).toBeGreaterThan(0);
  });
});

describe('command builders', () => {
  it('builds an install command with a pinned version', () => {
    expect(getInstallCommand('npm', 'react', '19.0.0')).toBe('npm install react@19.0.0');
    expect(getInstallCommand('pnpm', 'react', '19.0.0')).toBe('pnpm add react@19.0.0');
  });

  it('omits the version suffix when no version is given', () => {
    expect(getInstallCommand('yarn', 'react')).toBe('yarn add react');
  });

  it('applies the per-manager exact flag', () => {
    expect(getInstallCommand('npm', 'react', '19.0.0', true)).toBe('npm install --save-exact react@19.0.0');
    expect(getInstallCommand('yarn', 'react', '19.0.0', true)).toBe('yarn add --exact react@19.0.0');
    expect(getInstallCommand('bun', 'react', '19.0.0', true)).toBe('bun add --exact react@19.0.0');
  });

  it('builds the uninstall command per manager', () => {
    expect(getUninstallCommand('npm', 'react')).toBe('npm uninstall react');
    expect(getUninstallCommand('yarn', 'react')).toBe('yarn remove react');
    expect(getUninstallCommand('pnpm', 'react')).toBe('pnpm remove react');
    expect(getUninstallCommand('bun', 'react')).toBe('bun remove react');
  });

  it('builds the audit command per manager', () => {
    expect(getAuditCommand('npm')).toBe('npm audit --json');
    expect(getAuditCommand('pnpm')).toBe('pnpm audit --json');
  });

  // Without --json bun prints a human-readable summary, which never parsed.
  it('asks bun for machine-readable output', () => {
    expect(getAuditCommand('bun')).toBe('bun audit --json');
  });
});

describe('yarn major detection', () => {
  let projectPath: string;

  beforeEach(() => {
    projectPath = fs.mkdtempSync(path.join(os.tmpdir(), 'nvm-yarn-'));
  });

  afterEach(() => {
    fs.rmSync(projectPath, { recursive: true, force: true });
  });

  const writeFile = (name: string, contents: string): void => {
    fs.writeFileSync(path.join(projectPath, name), contents);
  };

  const classicLock = [
    '# THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.',
    '# yarn lockfile v1',
    '',
    '"@babel/code-frame@^7.0.0":',
    '  version "7.24.7"',
    '',
  ].join('\n');

  const berryLock = [
    '# This file is generated by running "yarn install" inside your project.',
    '# Manual changes might be lost - proceed with caution!',
    '',
    '__metadata:',
    '  version: 8',
    '  cacheKey: 10c0',
    '',
  ].join('\n');

  it('treats a yarn.lock with a __metadata block as berry', async () => {
    writeFile('yarn.lock', berryLock);
    await expect(isYarnBerry(projectPath)).resolves.toBe(true);
  });

  it('treats a classic yarn.lock as not berry', async () => {
    writeFile('yarn.lock', classicLock);
    await expect(isYarnBerry(projectPath)).resolves.toBe(false);
  });

  it('falls back to .yarnrc.yml when the lock file is absent', async () => {
    writeFile('.yarnrc.yml', 'nodeLinker: node-modules\n');
    await expect(isYarnBerry(projectPath)).resolves.toBe(true);
  });

  it('reports not berry when there is nothing to go on', async () => {
    await expect(isYarnBerry(projectPath)).resolves.toBe(false);
  });

  // Yarn 2+ removed `yarn audit`; running it there fails with "Couldn't find a
  // script named audit", which used to surface as an empty Security column.
  it('uses yarn npm audit for berry projects', async () => {
    writeFile('yarn.lock', berryLock);
    await expect(getAuditCommandForProject('yarn', projectPath)).resolves.toBe('yarn npm audit --json');
  });

  it('uses yarn audit for classic projects', async () => {
    writeFile('yarn.lock', classicLock);
    await expect(getAuditCommandForProject('yarn', projectPath)).resolves.toBe('yarn audit --json');
  });

  it.each(['npm', 'pnpm', 'bun'] as PackageManager[])('leaves the %s audit command untouched', async manager => {
    writeFile('.yarnrc.yml', 'nodeLinker: node-modules\n');
    await expect(getAuditCommandForProject(manager, projectPath)).resolves.toBe(getAuditCommand(manager));
  });
});

describe('parseAuditOutput', () => {
  it('parses the npm v7+ vulnerabilities map', () => {
    const output = JSON.stringify({
      vulnerabilities: {
        lodash: {
          severity: 'high',
          via: [{ title: 'Prototype pollution', range: '<4.17.21', url: 'https://example.test/advisory' }],
          fixAvailable: true,
        },
      },
      metadata: { vulnerabilities: { info: 0, low: 0, moderate: 0, high: 1, critical: 0 } },
    });

    const result = parseAuditOutput('npm', output);

    expect(result.vulnerabilities).toHaveLength(1);
    expect(result.vulnerabilities[0]).toMatchObject({
      packageName: 'lodash',
      severity: 'high',
      title: 'Prototype pollution',
      vulnerableVersions: '<4.17.21',
      patchedVersions: 'Available',
      url: 'https://example.test/advisory',
    });
    expect(result.metadata.vulnerabilities.high).toBe(1);
  });

  it('reports no fix when npm says none is available', () => {
    const output = JSON.stringify({
      vulnerabilities: { lodash: { severity: 'low', via: ['other-package'], fixAvailable: false } },
    });

    expect(parseAuditOutput('npm', output).vulnerabilities[0]).toMatchObject({
      title: 'Vulnerability in lodash',
      vulnerableVersions: '*',
      patchedVersions: 'Not available',
    });
  });

  it('parses the advisories map used by npm v6 and pnpm', () => {
    const output = JSON.stringify({
      advisories: {
        '1065803': {
          title: 'Regular Expression Denial of Service',
          severity: 'moderate',
          // eslint-disable-next-line @typescript-eslint/naming-convention
          module_name: 'minimatch',
          // eslint-disable-next-line @typescript-eslint/naming-convention
          vulnerable_versions: '<3.0.5',
          // eslint-disable-next-line @typescript-eslint/naming-convention
          patched_versions: '>=3.0.5',
          url: 'https://example.test/1065803',
        },
      },
    });

    expect(parseAuditOutput('pnpm', output).vulnerabilities[0]).toMatchObject({
      id: '1065803',
      packageName: 'minimatch',
      severity: 'moderate',
      patchedVersions: '>=3.0.5',
    });
  });

  // Yarn classic prints newline-delimited JSON. The parser used to run a single
  // JSON.parse over the whole output, which always threw, so the Security
  // column silently stayed empty for every yarn project.
  it('parses the newline-delimited output of yarn classic', () => {
    const output = [
      JSON.stringify({ type: 'info', data: 'No lockfile found.' }),
      JSON.stringify({
        type: 'auditAdvisory',
        data: {
          resolution: { id: 1065803, path: 'jest>minimatch' },
          advisory: {
            id: 1065803,
            title: 'Regular Expression Denial of Service',
            severity: 'high',
            // eslint-disable-next-line @typescript-eslint/naming-convention
            module_name: 'minimatch',
            // eslint-disable-next-line @typescript-eslint/naming-convention
            vulnerable_versions: '<3.0.5',
            // eslint-disable-next-line @typescript-eslint/naming-convention
            patched_versions: '>=3.0.5',
            url: 'https://example.test/1065803',
          },
        },
      }),
      JSON.stringify({
        type: 'auditSummary',
        data: {
          vulnerabilities: { info: 0, low: 0, moderate: 0, high: 1, critical: 0 },
          totalDependencies: 168,
        },
      }),
      '',
    ].join('\n');

    const result = parseAuditOutput('yarn', output);

    expect(result.vulnerabilities).toHaveLength(1);
    expect(result.vulnerabilities[0]).toMatchObject({
      id: '1065803',
      packageName: 'minimatch',
      severity: 'high',
      title: 'Regular Expression Denial of Service',
      vulnerableVersions: '<3.0.5',
      patchedVersions: '>=3.0.5',
      url: 'https://example.test/1065803',
    });
    expect(result.metadata.vulnerabilities.high).toBe(1);
  });

  // Yarn emits one auditAdvisory per dependency path, so a package pulled in
  // three ways used to be counted three times in the table.
  it('collapses the same yarn advisory reported for several dependency paths', () => {
    const advisory = {
      id: 1065803,
      title: 'Regular Expression Denial of Service',
      severity: 'high',
      // eslint-disable-next-line @typescript-eslint/naming-convention
      module_name: 'minimatch',
      // eslint-disable-next-line @typescript-eslint/naming-convention
      vulnerable_versions: '<3.0.5',
      // eslint-disable-next-line @typescript-eslint/naming-convention
      patched_versions: '>=3.0.5',
    };
    const output = ['jest>minimatch', 'eslint>minimatch', 'vite>minimatch']
      .map(dependencyPath =>
        JSON.stringify({ type: 'auditAdvisory', data: { resolution: { id: 1065803, path: dependencyPath }, advisory } })
      )
      .join('\n');

    expect(parseAuditOutput('yarn', output).vulnerabilities).toHaveLength(1);
  });

  it('keeps distinct advisories affecting the same package', () => {
    const base = {
      severity: 'moderate',
      // eslint-disable-next-line @typescript-eslint/naming-convention
      module_name: 'minimatch',
      // eslint-disable-next-line @typescript-eslint/naming-convention
      vulnerable_versions: '<3.0.5',
      // eslint-disable-next-line @typescript-eslint/naming-convention
      patched_versions: '>=3.0.5',
    };
    const output = [
      JSON.stringify({ type: 'auditAdvisory', data: { advisory: { ...base, id: 1, title: 'First' } } }),
      JSON.stringify({ type: 'auditAdvisory', data: { advisory: { ...base, id: 2, title: 'Second' } } }),
    ].join('\n');

    expect(parseAuditOutput('yarn', output).vulnerabilities).toHaveLength(2);
  });

  it('skips non-JSON progress lines mixed into the stream', () => {
    const output = [
      'Fetching advisories...',
      JSON.stringify({
        type: 'auditAdvisory',
        // eslint-disable-next-line @typescript-eslint/naming-convention
        data: { advisory: { id: 7, title: 'Bad', severity: 'critical', module_name: 'left-pad' } },
      }),
      'Done.',
    ].join('\n');

    const result = parseAuditOutput('yarn', output);

    expect(result.vulnerabilities).toHaveLength(1);
    expect(result.vulnerabilities[0]).toMatchObject({
      packageName: 'left-pad',
      severity: 'critical',
      // Absent fields fall back rather than surfacing as undefined in the table
      vulnerableVersions: '*',
      patchedVersions: 'Not available',
    });
  });

  it('reports an unrecognised severity as info instead of dropping the entry', () => {
    const output = JSON.stringify({
      advisories: {
        // eslint-disable-next-line @typescript-eslint/naming-convention
        '1': { title: 'Odd', severity: 'catastrophic', module_name: 'left-pad' },
      },
    });

    expect(parseAuditOutput('npm', output).vulnerabilities[0]).toMatchObject({
      packageName: 'left-pad',
      severity: 'info',
    });
  });

  it('ignores advisories with no package name', () => {
    const output = JSON.stringify({ advisories: { '1': { title: 'Nameless', severity: 'high' } } });

    expect(parseAuditOutput('npm', output).vulnerabilities).toEqual([]);
  });

  // Bun reports the npm bulk advisory response: package name -> advisories,
  // with the name only present as the map key.
  it('parses the bulk advisory map that bun reports', () => {
    const output = JSON.stringify({
      lodash: [
        {
          id: 1065803,
          title: 'Prototype pollution',
          severity: 'high',
          // eslint-disable-next-line @typescript-eslint/naming-convention
          vulnerable_versions: '<4.17.21',
          url: 'https://example.test/1065803',
        },
      ],
    });

    const result = parseAuditOutput('bun', output);

    expect(result.vulnerabilities).toHaveLength(1);
    expect(result.vulnerabilities[0]).toMatchObject({
      id: '1065803',
      packageName: 'lodash',
      severity: 'high',
      title: 'Prototype pollution',
      vulnerableVersions: '<4.17.21',
    });
  });

  it('handles several packages in a bulk advisory map', () => {
    const output = JSON.stringify({
      lodash: [{ id: 1, title: 'One', severity: 'high' }],
      minimatch: [
        { id: 2, title: 'Two', severity: 'moderate' },
        { id: 3, title: 'Three', severity: 'low' },
      ],
    });

    const result = parseAuditOutput('bun', output);

    expect(result.vulnerabilities).toHaveLength(3);
    expect(result.vulnerabilities.map(v => v.packageName)).toEqual(['lodash', 'minimatch', 'minimatch']);
  });

  // npm 6 ships top-level `actions` and `muted` arrays. Read as a bulk advisory
  // map they would invent vulnerabilities for packages named "actions"/"muted".
  it('does not mistake the npm 6 actions array for advisories', () => {
    const output = JSON.stringify({
      actions: [{ action: 'install', module: 'lodash', target: '4.17.21', isMajor: false, resolves: [] }],
      muted: [],
      advisories: {
        '1065803': {
          title: 'Prototype pollution',
          severity: 'high',
          // eslint-disable-next-line @typescript-eslint/naming-convention
          module_name: 'lodash',
        },
      },
    });

    const result = parseAuditOutput('npm', output);

    expect(result.vulnerabilities).toHaveLength(1);
    expect(result.vulnerabilities[0]!.packageName).toBe('lodash');
  });

  it('ignores array entries that carry no severity', () => {
    const output = JSON.stringify({ lodash: [{ title: 'No severity here' }] });

    expect(parseAuditOutput('bun', output).vulnerabilities).toEqual([]);
  });

  it('returns an empty result for output that is not JSON', () => {
    const result = parseAuditOutput('bun', 'audit found 3 vulnerabilities\n');

    expect(result.vulnerabilities).toEqual([]);
    expect(result.metadata.vulnerabilities).toEqual({ info: 0, low: 0, moderate: 0, high: 0, critical: 0 });
  });

  it('returns an empty result for JSON without a recognised shape', () => {
    expect(parseAuditOutput('npm', JSON.stringify({ somethingElse: true })).vulnerabilities).toEqual([]);
  });
});
